Repository codesquad-member-2020/todo-6, pull requests merged in 2020-04, with the labels that each got.

#24 [#10] Chore: 개발환경 구축
  FE/.babelrc
  FE/.eslintrc.js
  FE/.gitignore
  FE/package-lock.json
  FE/package.json
  FE/src/index.html
  FE/src/scss/main.scss
  FE/src/ts/main.ts
  FE/tsconfig.json
  FE/webpack.config.js
Labels: FE, feature

#34 [#3] 메인 페이지 마크업 작성
  FE/package-lock.json
  FE/package.json
  FE/src/css/main.css
  FE/src/index.html
  FE/src/scss/main.scss
  FE/src/ts/main.ts
  FE/webpack.config.js
Labels: FE, feature

#35 [#4] Style: 메인 CSS 스타일링
  FE/src/css/main.css
  FE/src/index.html
Labels: FE, feature

#37 사이드 메뉴 CSS 작성 완료
  FE/src/css/main.css
  FE/src/index.html
Labels: FE, feature

#39 [#14] 모달 레이어 CSS 작성
  FE/src/css/main.css
  FE/src/index.html
Labels: FE, feature

#41 [#23] update: db 재설계
  BE/src/main/java/com/codesquad/todo/domain/Activity.java
  BE/src/main/java/com/codesquad/todo/domain/Card.java
  BE/src/main/java/com/codesquad/todo/domain/Project.java
  BE/src/main/java/com/codesquad/todo/domain/ProjectRepository.java
  BE/src/main/java/com/codesquad/todo/domain/Section.java
  BE/src/main/java/com/codesquad/todo/domain/User.java
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: BE

#38 [#22] 스토리보드로 화면 구성
  iOS/.gitignore
  iOS/README.md
  iOS/Todo/Todo.xcodeproj/project.pbxproj
  iOS/Todo/Todo.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/Todo/Todo.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/Todo/Todo/AppDelegate.swift
  iOS/Todo/Todo/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/Todo/Todo/Assets.xcassets/Contents.json
  iOS/Todo/Todo/Base.lproj/LaunchScreen.storyboard
  iOS/Todo/Todo/Base.lproj/Main.storyboard
  iOS/Todo/Todo/Info.plist
  iOS/Todo/Todo/SceneDelegate.swift
  iOS/Todo/Todo/ViewController.swift
  iOS/Todo/TodoTests/Info.plist
  iOS/Todo/TodoTests/TodoTests.swift
Labels: iOS

#44 [#5] 스켈레톤 코드 작성
  FE/package-lock.json
  FE/package.json
  FE/src/css/base/_layout.css
  FE/src/css/base/_typography.css
  FE/src/css/base/_webfont.css
  FE/src/css/components/_button.css
  FE/src/css/components/_card.css
  FE/src/css/components/_column.css
  FE/src/css/components/_dimmedLayer.css
  FE/src/css/components/_header.css
  FE/src/css/components/_modal.css
  FE/src/css/components/_sidemenu.css
  FE/src/css/components/_textarea.css
  FE/src/css/main.css
  FE/src/css/utils/_utilClasses.css
  FE/src/index.html
  FE/src/ts/components/card.ts
  FE/src/ts/components/column.ts
  FE/src/ts/components/eventManager.ts
  FE/src/ts/components/fetch.ts
  FE/src/ts/components/inputForm.ts
  FE/src/ts/components/modal.ts
  FE/src/ts/components/sidemenu.ts
  FE/src/ts/main.ts
  FE/src/ts/utils/constants.ts
  FE/src/ts/utils/utils.ts
  FE/webpack.config.js
Labels: FE, feature

#42 [#23] fix: db 변경
  BE/src/main/java/com/codesquad/todo/domain/User.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: BE

#45 [#23] DB 수정시 변경되지 않은 도메인 수정
  BE/src/main/java/com/codesquad/todo/domain/Activity.java
  BE/src/main/java/com/codesquad/todo/domain/Card.java
  BE/src/main/java/com/codesquad/todo/domain/Project.java
  BE/src/main/resources/schema.sql
Labels: BE

#51 [#6] 카드 추가 기능 구현
  FE/src/css/components/_card.css
  FE/src/ts/components/card.ts
  FE/src/ts/components/column.ts
  FE/src/ts/components/container.ts
  FE/src/ts/components/eventManager.ts
  FE/src/ts/components/fetch.ts
  FE/src/ts/components/inputForm.ts
  FE/src/ts/components/sidemenu.ts
  FE/src/ts/main.ts
  FE/src/ts/utils/constants.ts
Labels: FE, feature

#53 [#10] 할 일 카드 삭제 기능 구현
  FE/src/css/components/_textarea.css
  FE/src/ts/components/card.ts
  FE/src/ts/components/eventManager.ts
  FE/src/ts/components/fetch.ts
  FE/src/ts/components/inputForm.ts
  FE/src/ts/components/modal.ts
  FE/webpack.config.js
Labels: FE, feature

#54 FE 프로젝트 1주차 리뷰 요청
  FE/.babelrc
  FE/.eslintrc.js
  FE/.gitignore
  FE/.keep
  FE/package-lock.json
  FE/package.json
  FE/src/css/base/_layout.css
  FE/src/css/base/_typography.css
  FE/src/css/base/_webfont.css
  FE/src/css/components/_button.css
  FE/src/css/components/_card.css
  FE/src/css/components/_column.css
  FE/src/css/components/_dimmedLayer.css
  FE/src/css/components/_header.css
  FE/src/css/components/_modal.css
  FE/src/css/components/_sidemenu.css
  FE/src/css/components/_textarea.css
  FE/src/css/main.css
  FE/src/css/utils/_utilClasses.css
  FE/src/index.html
  FE/src/ts/components/card.ts
  FE/src/ts/components/column.ts
  FE/src/ts/components/container.ts
  FE/src/ts/components/eventManager.ts
  FE/src/ts/components/fetch.ts
  FE/src/ts/components/inputForm.ts
  FE/src/ts/components/modal.ts
  FE/src/ts/components/sidemenu.ts
  FE/src/ts/main.ts
  FE/src/ts/utils/constants.ts
  FE/src/ts/utils/utils.ts
  FE/tsconfig.json
  FE/webpack.config.js
Labels: FE, FE 리뷰요청

#55 [#11] 카드 삭제 기능 구현
  FE/src/css/components/_dimmedLayer.css
  FE/src/css/components/_header.css
  FE/src/css/components/_modal.css
  FE/src/index.html
  FE/src/ts/components/card.ts
  FE/src/ts/components/column.ts
  FE/src/ts/components/container.ts
  FE/src/ts/components/eventManager.ts
  FE/src/ts/components/fetch.ts
  FE/src/ts/components/inputForm.ts
  FE/src/ts/components/modal.ts
  FE/src/ts/main.ts
  FE/src/ts/utils/constants.ts
  FE/src/ts/utils/htmlElement.ts
Labels: FE, feature

#56 Interceptor를 이용한 jwt token 인증 시스템 구현
  BE/build.gradle
  BE/src/main/java/com/codesquad/todo/HttpInterceptor.java
  BE/src/main/java/com/codesquad/todo/WebConfig.java
  BE/src/main/java/com/codesquad/todo/domain/Project.java
  BE/src/main/java/com/codesquad/todo/domain/User.java
  BE/src/main/java/com/codesquad/todo/exeption/CustomAdvice.java
  BE/src/main/java/com/codesquad/todo/exeption/NotFoundData.java
  BE/src/main/java/com/codesquad/todo/service/JwtService.java
  BE/src/main/resources/data.sql
Labels: BE, feature

#57 카드 생성
  BE/src/main/java/com/codesquad/todo/controller/CardController.java
  BE/src/main/java/com/codesquad/todo/domain/Activity.java
  BE/src/main/java/com/codesquad/todo/domain/Card.java
  BE/src/main/java/com/codesquad/todo/domain/Project.java
  BE/src/main/java/com/codesquad/todo/domain/Section.java
  BE/src/main/java/com/codesquad/todo/domain/User.java
  BE/src/main/java/com/codesquad/todo/dto/CardDto.java
  BE/src/main/java/com/codesquad/todo/exeption/NotFoundData.java
  BE/src/main/java/com/codesquad/todo/service/JwtService.java
  BE/src/main/java/com/codesquad/todo/service/TodoService.java
Labels: BE, feature

#58 [#15] 카드 수정 기능 구현
  FE/src/css/components/_card.css
  FE/src/ts/components/card.ts
  FE/src/ts/components/column.ts
  FE/src/ts/components/columnWrap.ts
  FE/src/ts/components/container.ts
  FE/src/ts/components/eventManager.ts
  FE/src/ts/components/fetch.ts
  FE/src/ts/components/header.ts
  FE/src/ts/components/inputForm.ts
  FE/src/ts/components/modal.ts
  FE/src/ts/main.ts
  FE/src/ts/utils/utils.ts
  FE/tsconfig.json
Labels: FE, feature

#59 [#29] 카드 삭제 기능 추가
  BE/src/main/java/com/codesquad/todo/controller/CardController.java
  BE/src/main/java/com/codesquad/todo/domain/Project.java
  BE/src/main/java/com/codesquad/todo/domain/SectionRepository.java
  BE/src/main/java/com/codesquad/todo/service/TodoService.java
Labels: BE, feature

#63 [#28] 카드 수정 로직 구현
  BE/src/main/java/com/codesquad/todo/controller/CardController.java
  BE/src/main/java/com/codesquad/todo/domain/Activity.java
  BE/src/main/java/com/codesquad/todo/domain/SectionRepository.java
  BE/src/main/java/com/codesquad/todo/service/TodoService.java
Labels: BE, feature

#71 [#31] 전체 목록 출력
  BE/src/main/java/com/codesquad/todo/controller/TodoController.java
  BE/src/main/java/com/codesquad/todo/domain/ProjectRepository.java
  BE/src/main/java/com/codesquad/todo/domain/Section.java
  BE/src/main/java/com/codesquad/todo/dto/CardDto.java
  BE/src/main/java/com/codesquad/todo/dto/SectionDto.java
  BE/src/main/java/com/codesquad/todo/dto/TempSectionDTO.java
  BE/src/main/java/com/codesquad/todo/service/TodoService.java
Labels: BE, feature

#78 [#77] refactor: 스트링 하드 코딩 제외
  BE/src/main/java/com/codesquad/todo/controller/ActivityController.java
  BE/src/main/java/com/codesquad/todo/controller/CardController.java
  BE/src/main/java/com/codesquad/todo/controller/TodoController.java
  BE/src/main/java/com/codesquad/todo/domain/Activity.java
  BE/src/main/java/com/codesquad/todo/exeption/UnauthorizedException.java
  BE/src/main/java/com/codesquad/todo/service/JwtService.java
  BE/src/main/java/com/codesquad/todo/service/TodoService.java
  BE/src/main/java/com/codesquad/todo/utill/Action.java
  BE/src/main/java/com/codesquad/todo/utill/ErrorMessages.java
  BE/src/main/java/com/codesquad/todo/utill/SuccessMessages.java
Labels: BE, refactor

#80 [#77] 함수, 변수명 정리
  BE/src/main/java/com/codesquad/todo/controller/TodoController.java
  BE/src/main/java/com/codesquad/todo/domain/Activity.java
  BE/src/main/java/com/codesquad/todo/domain/ActivityRepository.java
  BE/src/main/java/com/codesquad/todo/domain/CardRepository.java
  BE/src/main/java/com/codesquad/todo/domain/ProjectRepository.java
  BE/src/main/java/com/codesquad/todo/dto/TempSectionDTO.java
  BE/src/main/java/com/codesquad/todo/service/TodoService.java
Labels: BE, refactor

#82 [#16] 드래그 앤 드롭 기능 구현
  FE/src/css/components/_card.css
  FE/src/css/components/_column.css
  FE/src/css/components/_textarea.css
  FE/src/css/utils/_utilClasses.css
  FE/src/ts/components/card.ts
  FE/src/ts/components/column.ts
  FE/src/ts/components/columnWrap.ts
  FE/src/ts/components/dragAndDrop.ts
  FE/src/ts/components/eventManager.ts
  FE/src/ts/components/fetch.ts
  FE/src/ts/components/modal.ts
  FE/src/ts/main.ts
  FE/src/ts/utils/constants.ts
  FE/src/ts/utils/htmlElement.ts
  FE/src/ts/utils/utils.ts
Labels: FE, feature

#83 [#30] feat: 카드 이동
  BE/src/main/java/com/codesquad/todo/controller/CardController.java
  BE/src/main/java/com/codesquad/todo/domain/Section.java
  BE/src/main/java/com/codesquad/todo/exeption/CustomAdvice.java
  BE/src/main/java/com/codesquad/todo/service/TodoService.java
  BE/src/main/java/com/codesquad/todo/utill/SuccessMessages.java
Labels: BE, feature

#90 [#18] 사이드 메뉴 구현
  FE/src/css/components/_column.css
  FE/src/css/components/_dimmedLayer.css
  FE/src/css/components/_modal.css
  FE/src/css/components/_sidemenu.css
  FE/src/css/utils/_utilClasses.css
  FE/src/index.html
  FE/src/ts/components/activity.ts
  FE/src/ts/components/card.ts
  FE/src/ts/components/column.ts
  FE/src/ts/components/columnWrap.ts
  FE/src/ts/components/dragAndDrop.ts
  FE/src/ts/components/eventManager.ts
  FE/src/ts/components/fetch.ts
  FE/src/ts/components/header.ts
  FE/src/ts/components/modal.ts
  FE/src/ts/components/sidemenu.ts
  FE/src/ts/main.ts
  FE/src/ts/utils/constants.ts
  FE/src/ts/utils/htmlElement.ts
  FE/src/ts/utils/utils.ts
Labels: FE, feature

#91 FE 진행사항
  FE/src/css/components/_card.css
  FE/src/css/components/_column.css
  FE/src/css/components/_dimmedLayer.css
  FE/src/css/components/_header.css
  FE/src/css/components/_modal.css
  FE/src/css/components/_sidemenu.css
  FE/src/css/components/_textarea.css
  FE/src/css/utils/_utilClasses.css
  FE/src/index.html
  FE/src/ts/components/activity.ts
  FE/src/ts/components/card.ts
  FE/src/ts/components/column.ts
  FE/src/ts/components/columnWrap.ts
  FE/src/ts/components/container.ts
  FE/src/ts/components/dragAndDrop.ts
  FE/src/ts/components/eventManager.ts
  FE/src/ts/components/fetch.ts
  FE/src/ts/components/header.ts
  FE/src/ts/components/inputForm.ts
  FE/src/ts/components/modal.ts
  FE/src/ts/components/sidemenu.ts
  FE/src/ts/main.ts
  FE/src/ts/utils/constants.ts
  FE/src/ts/utils/htmlElement.ts
  FE/src/ts/utils/utils.ts
  FE/tsconfig.json
Labels: FE
